[project]
name = "VRCTwitterImageLoader"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "VarYU", email = "varyu.vrc@gmail.com" }
]
dependencies = [
    "selenium>=4.15.2",
    "pillow>=10.1.0",
    "ipykernel>=6.26.0",
    "ruff>=0.1.6",
    "get-chrome-driver>=1.3.19",
]
readme = "README.md"
requires-python = ">= 3.11"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = []

[tool.hatch.metadata]
allow-direct-references = true
