[project]
name = "VRCTwitterImageLoader"
version = "0.2.0"
description = "Upload Twitter images to GitHub Pages for VRChat"
authors = [
    { name = "VarYU", email = "varyu.vrc@gmail.com" }
]
dependencies = [
    "selenium>=4.15.2",
    "pillow>=10.1.0",
    "chromedriver-binary-sync>=0.2.2",
    "pandas>=2.2.2",
]
readme = "README.md"
requires-python = ">= 3.10"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "ipykernel>=6.29.4",
    "ruff>=0.3.7",
]

[tool.hatch.metadata]
allow-direct-references = true
