name: Python Script Execution

on:
  workflow_dispatch:  # 手動実行用のトリガー
  schedule:
    - cron: '0 19 * * *' # UTC時間で19時（日本時間で翌朝4時）

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Rye
      uses: baptiste0928/cargo-install@v2
      with:
        crate: rye
        git: https://github.com/mitsuhiko/rye
        branch: main

    - name: Install Dependencies
      run: |
        rye sync

    - name: Install Chrome
      run: |
        sudo wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo apt update
        sudo apt-get install google-chrome-stable

    - name: Install Japanese Fonts
      run: |
        sudo apt-get update
        sudo apt-get install -y fonts-ipafont

    - name: Run Python Script
      run: |
        rye run python src/VRCTwitterImageLoader/twitter_image.py

    - name: Upload Screenshots as Artifacts
      uses: actions/upload-pages-artifact@v1
      with:
        path: src/VRCTwitterImageLoader/pages

  deploy:
    needs: run-python-script
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
    steps:
      - uses: actions/deploy-pages@v2